### ISSUE TITLE
Setting custom port seems to fail

### ISSUE THREAD

**Issue by mvellinger** [rich-iannone/blastula#4]
When setting a port other than 465, sending email fails, and the error message seems to imply Blastula attempted to use port 465 rather than the specified port.

I tried with both my private mail server and outlook.com

`Sys.setenv(bls_sender = "m.vellinger@outlook.com", 
           bls_host = "smtp-mail.outlook.com",
           bls_username = "m.vellinger@outlook.com",
           bls_password = "*********",
           bls_port = 587)
           
send_email_out(
  message = email_object,
  from = "m.vellinger@outlook.com",
  recipients = "m.vellinger@outlook.com",
  subject = "Test mail.",
  sender = Sys.getenv("bls_sender"),
  host = Sys.getenv("bls_host"),
  port = Sys.getenv("bls_port"),
  user = Sys.getenv("bls_username"),
  password = Sys.getenv("bls_password"))`

And the resulting error:

`org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp-mail.outlook.com:465
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410)
	at org.apache.commons.mail.Email.send(Email.java:1437)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at RJavaTools.invokeMethod(RJavaTools.java:386)
Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp-mail.outlook.com, 465; timeout 60000;
  nested exception is:
	java.net.ConnectException: Connection timed out: connect
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2053)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:697)
	at javax.mail.Service.connect(Service.java:386)
	at javax.mail.Service.connect(Service.java:245)
	at javax.mail.Service.connect(Service.java:194)
	at javax.mail.Transport.send0(Transport.java:253)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
	... 6 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:310)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:215)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2019)
	... 13 more
NULL
Error: EmailException (Java): Sending the email to the following server failed : smtp-mail.outlook.com:465`

**Comment by rich-iannone** [comment]
@mvellinger 
Aha! Had this exact issue before (take a look at issue #1) I think the trick is to set `use_SSL = FALSE` and, for Outlook, set `use_tls = TRUE`. Try using the `debug = TRUE` in the `send_mail_out()` call to get debug messages and verify that the correct port is being used.

**Comment by mvellinger** [comment]
Yup! that did the trick!

oh, btw, in the documentation, in the section where you mention using environment variables, there is a small error where you "set the port" with the bls_host variable ;)

**Comment by rich-iannone** [comment]
@mvellinger thanks for checking and verifying this. My plan is to switch the method in sending the email, so, I’m hoping this issue will resolve itself once that change is made. 

Thanks for pointing out the README mistake! Fixed that.
